# Generated by Django 4.2.7 on 2025-11-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_repair_alter_user_role_repairitem_repair_technician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='return_policy_days',
            field=models.IntegerField(default=7, help_text='Number of days for returns'),
        ),
        migrations.AddField(
            model_name='store',
            name='tax_id',
            field=models.CharField(blank=True, help_text='VAT/TIN number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('mobile', 'Mobile Payment'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20),
        ),
    ]
